import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sound from "./components/Sound/Sound";
import SoundButton from "./components/soundButton/SoundButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Interactive LEGO Spaceship Assembly | Asaf Levi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sound />
        {children}
        <SoundButton />
      </body>
    </html>
  );
  
}


